algoritmo "Seja bem vindo"

// Função : Exibir na tela o seja bem vindo usuario
// Autor : Barbara
// Data : 17/12/2018

// edit. 2022 - Código especial, primeiro em portugol. Meses depois de sua criação eu decidi que técnologia seria minha área.

var
Nome: caracter

inicio
// Seção de Comandos

escreval("informe o seu nome")
leia(nome)

escreval("Olá ", nome, " seja bem vindo")

fimalgoritmo
